import type { Locale } from "@/lib/types";
import type {
  Element,
  HabitatId,
  LearnEntry,
  MoveId,
  Species,
  SpeciesId,
} from "./types";

function ls(...entries: LearnEntry[]): LearnEntry[] {
  return entries;
}

export const SPECIES: Record<SpeciesId, Species> = {
  "ember-cub": {
    id: "ember-cub",
    element: "ember",
    baseHp: 30,
    baseAtk: 8,
    baseDef: 5,
    baseSpd: 8,
    rarity: "common",
    learnset: ls(
      { level: 1, moveId: "scratch" },
      { level: 1, moveId: "ember-lash" },
      { level: 3, moveId: "focus" },
      { level: 5, moveId: "inferno" },
    ),
  },
  "tide-sprite": {
    id: "tide-sprite",
    element: "tide",
    baseHp: 34,
    baseAtk: 7,
    baseDef: 7,
    baseSpd: 6,
    rarity: "common",
    learnset: ls(
      { level: 1, moveId: "scratch" },
      { level: 1, moveId: "tide-bolt" },
      { level: 3, moveId: "heal-lick" },
      { level: 5, moveId: "tidal-crush" },
    ),
  },
  "gale-finch": {
    id: "gale-finch",
    element: "gale",
    baseHp: 26,
    baseAtk: 8,
    baseDef: 4,
    baseSpd: 12,
    rarity: "common",
    learnset: ls(
      { level: 1, moveId: "scratch" },
      { level: 1, moveId: "gale-cut" },
      { level: 3, moveId: "quicken" },
      { level: 5, moveId: "focus" },
    ),
  },
  "moss-brute": {
    id: "moss-brute",
    element: "moss",
    baseHp: 36,
    baseAtk: 6,
    baseDef: 8,
    baseSpd: 4,
    rarity: "common",
    learnset: ls(
      { level: 1, moveId: "scratch" },
      { level: 1, moveId: "moss-slam" },
      { level: 3, moveId: "harden" },
      { level: 4, moveId: "guard" },
    ),
  },
  "spark-mite": {
    id: "spark-mite",
    element: "spark",
    baseHp: 22,
    baseAtk: 10,
    baseDef: 3,
    baseSpd: 11,
    rarity: "uncommon",
    learnset: ls(
      { level: 1, moveId: "scratch" },
      { level: 1, moveId: "spark-jolt" },
      { level: 3, moveId: "quicken" },
      { level: 4, moveId: "focus" },
    ),
  },
  "shade-pup": {
    id: "shade-pup",
    element: "shade",
    baseHp: 28,
    baseAtk: 8,
    baseDef: 5,
    baseSpd: 9,
    rarity: "uncommon",
    learnset: ls(
      { level: 1, moveId: "scratch" },
      { level: 1, moveId: "shade-bite" },
      { level: 3, moveId: "heal-lick" },
      { level: 5, moveId: "abyss-fang" },
    ),
  },
  "cinder-fox": {
    id: "cinder-fox",
    element: "ember",
    baseHp: 30,
    baseAtk: 11,
    baseDef: 6,
    baseSpd: 10,
    rarity: "uncommon",
    learnset: ls(
      { level: 1, moveId: "ember-lash" },
      { level: 1, moveId: "scratch" },
      { level: 3, moveId: "focus" },
      { level: 4, moveId: "inferno" },
    ),
  },
  "reef-guard": {
    id: "reef-guard",
    element: "tide",
    baseHp: 40,
    baseAtk: 8,
    baseDef: 11,
    baseSpd: 5,
    rarity: "uncommon",
    learnset: ls(
      { level: 1, moveId: "tide-bolt" },
      { level: 1, moveId: "guard" },
      { level: 3, moveId: "harden" },
      { level: 5, moveId: "tidal-crush" },
    ),
  },
  "storm-owl": {
    id: "storm-owl",
    element: "gale",
    baseHp: 28,
    baseAtk: 11,
    baseDef: 6,
    baseSpd: 13,
    rarity: "rare",
    learnset: ls(
      { level: 1, moveId: "gale-cut" },
      { level: 1, moveId: "quicken" },
      { level: 3, moveId: "scratch" },
      { level: 4, moveId: "focus" },
    ),
  },
  "root-titan": {
    id: "root-titan",
    element: "moss",
    baseHp: 48,
    baseAtk: 10,
    baseDef: 12,
    baseSpd: 3,
    rarity: "rare",
    learnset: ls(
      { level: 1, moveId: "moss-slam" },
      { level: 1, moveId: "harden" },
      { level: 3, moveId: "guard" },
      { level: 5, moveId: "heal-lick" },
    ),
  },
  "volt-drake": {
    id: "volt-drake",
    element: "spark",
    baseHp: 34,
    baseAtk: 14,
    baseDef: 7,
    baseSpd: 10,
    rarity: "rare",
    learnset: ls(
      { level: 1, moveId: "spark-jolt" },
      { level: 1, moveId: "scratch" },
      { level: 3, moveId: "focus" },
      { level: 4, moveId: "quicken" },
    ),
  },
  "night-wraith": {
    id: "night-wraith",
    element: "shade",
    baseHp: 32,
    baseAtk: 13,
    baseDef: 7,
    baseSpd: 12,
    rarity: "rare",
    learnset: ls(
      { level: 1, moveId: "shade-bite" },
      { level: 1, moveId: "scratch" },
      { level: 3, moveId: "quicken" },
      { level: 5, moveId: "abyss-fang" },
    ),
  },
  "boss-hydra": {
    id: "boss-hydra",
    element: "shade",
    baseHp: 100,
    baseAtk: 7,
    baseDef: 5,
    baseSpd: 6,
    rarity: "boss",
    learnset: ls(
      { level: 1, moveId: "abyss-fang" },
      { level: 1, moveId: "shade-bite" },
      { level: 1, moveId: "guard" },
      { level: 1, moveId: "scratch" },
    ),
  },
};

export const STARTER_IDS: SpeciesId[] = [
  "ember-cub",
  "tide-sprite",
  "gale-finch",
];

export const WILD_POOL: SpeciesId[] = [
  "ember-cub",
  "tide-sprite",
  "gale-finch",
  "moss-brute",
  "spark-mite",
  "shade-pup",
  "cinder-fox",
  "reef-guard",
  "storm-owl",
  "root-titan",
  "volt-drake",
  "night-wraith",
];

export const EARLY_POOL: SpeciesId[] = [
  "ember-cub",
  "tide-sprite",
  "gale-finch",
  "moss-brute",
];

export const ELEMENT_COLOR: Record<Element, string> = {
  ember: "#c45c2a",
  tide: "#2a7cad",
  gale: "#5a8fbf",
  moss: "#2f8a5b",
  spark: "#c9a227",
  shade: "#5b4b8a",
};

export type LocaleLabel = {
  species: Record<SpeciesId, string>;
  elements: Record<Element, string>;
  habitats: Record<HabitatId, string>;
  nodes: Record<
    "battle" | "elite" | "shop" | "event" | "rest" | "boss" | "start" | "habitat",
    string
  >;
  moves: Record<MoveId, { name: string; description: string }>;
  events: Record<string, { title: string; body: string; choices: Record<string, string> }>;
  shop: Record<"heal" | "buffAtk" | "buffDef" | "recruit" | "sell", string>;
  ui: Record<string, string>;
};

const moveCopyEn: LocaleLabel["moves"] = {
  scratch: { name: "Scratch", description: "A basic strike." },
  "ember-lash": { name: "Ember Lash", description: "Ember whip attack." },
  "tide-bolt": { name: "Tide Bolt", description: "A pressurized water shot." },
  "gale-cut": { name: "Gale Cut", description: "A slicing wind slash." },
  "moss-slam": { name: "Moss Slam", description: "A heavy earthy smash." },
  "spark-jolt": { name: "Spark Jolt", description: "A sharp electric sting." },
  "shade-bite": { name: "Shade Bite", description: "A shadowy chomp." },
  "heal-lick": { name: "Heal Lick", description: "Restore some HP." },
  focus: { name: "Focus", description: "+2 ATK (permanent this run)." },
  harden: { name: "Harden", description: "+2 DEF (permanent this run)." },
  quicken: { name: "Quicken", description: "+2 SPD (permanent this run)." },
  guard: { name: "Guard", description: "+4 DEF for this round." },
  inferno: { name: "Inferno", description: "A fierce ember blast." },
  "tidal-crush": { name: "Tidal Crush", description: "Crushing tide force." },
  "abyss-fang": { name: "Abyss Fang", description: "A deep-shade bite." },
};

const moveCopyEs: LocaleLabel["moves"] = {
  scratch: { name: "Arañazo", description: "Golpe básico." },
  "ember-lash": { name: "Látigo Ember", description: "Ataque de fuego." },
  "tide-bolt": { name: "Rayo de Marea", description: "Disparo de agua a presión." },
  "gale-cut": { name: "Corte Vendaval", description: "Tajo de viento." },
  "moss-slam": { name: "Golpe Musgo", description: "Embate terrestre." },
  "spark-jolt": { name: "Chispa", description: "Picadura eléctrica." },
  "shade-bite": { name: "Mordida Sombra", description: "Mordisco oscuro." },
  "heal-lick": { name: "Lengüetazo Curativo", description: "Recupera HP." },
  focus: { name: "Enfoque", description: "+2 ATK (permanente en la run)." },
  harden: { name: "Endurecer", description: "+2 DEF (permanente en la run)." },
  quicken: { name: "Agilidad", description: "+2 SPD (permanente en la run)." },
  guard: { name: "Guardia", description: "+4 DEF esta ronda." },
  inferno: { name: "Infierno", description: "Explosión de fuego." },
  "tidal-crush": { name: "Aplastamareas", description: "Fuerza de marea." },
  "abyss-fang": { name: "Colmillo Abismo", description: "Mordida de sombra profunda." },
};

export const copy: Record<Locale, LocaleLabel> = {
  en: {
    species: {
      "ember-cub": "Ember Cub",
      "tide-sprite": "Tide Sprite",
      "gale-finch": "Gale Finch",
      "moss-brute": "Moss Brute",
      "spark-mite": "Spark Mite",
      "shade-pup": "Shade Pup",
      "cinder-fox": "Cinder Fox",
      "reef-guard": "Reef Guard",
      "storm-owl": "Storm Owl",
      "root-titan": "Root Titan",
      "volt-drake": "Volt Drake",
      "night-wraith": "Night Wraith",
      "boss-hydra": "Abyss Hydra",
    },
    elements: {
      ember: "Ember",
      tide: "Tide",
      gale: "Gale",
      moss: "Moss",
      spark: "Spark",
      shade: "Shade",
    },
    habitats: {
      cave: "Cave",
      grassland: "Grassland",
      forest: "Forest",
      river: "River",
      sea: "Sea",
      beach: "Beach",
      desert: "Desert",
      swamp: "Swamp",
    },
    nodes: {
      start: "Camp",
      battle: "Battle",
      elite: "Elite",
      shop: "Shop",
      event: "Event",
      rest: "Rest",
      boss: "Boss",
      habitat: "Wilds",
    },
    moves: moveCopyEn,
    events: {
      spring: {
        title: "Hidden spring",
        body: "A warm spring bubbles between the stones. Your beasts drink deeply.",
        choices: {
          heal: "Rest and heal the party (50% + moves)",
          gold: "Bottle the water (+18 gold)",
        },
      },
      shrine: {
        title: "Weathered shrine",
        body: "An old shrine hums with residual power. Something answers your touch.",
        choices: {
          atk: "Offer a fang (+2 ATK to all)",
          def: "Offer a shell (+2 DEF to all)",
        },
      },
      trader: {
        title: "Wandering trader",
        body: "A masked trader offers a restless cage. Inside, a wild beast watches you.",
        choices: {
          take: "Accept the beast (if you have room)",
          gold: "Buy the cage empty (+25 gold, skip beast)",
        },
      },
      curse: {
        title: "Cursed thicket",
        body: "Thorns drip with night sap. Crossing costs something.",
        choices: {
          pay: "Cut through (−8 HP each)",
          bribe: "Leave an offering (−20 gold, safe)",
        },
      },
      campfire: {
        title: "Quiet campfire",
        body: "Embers crackle. Your beasts curl up and recover.",
        choices: {
          heal: "Sleep until dawn (heal 50% + moves)",
          train: "Spar lightly (+1 ATK, heal 50% + moves)",
        },
      },
      release: {
        title: "Open meadow",
        body: "A calm clearing. One of your beasts could return to the wild here.",
        choices: {
          keep: "Keep the whole party",
          free: "Release",
        },
      },
      wilds: {
        title: "Wild trail",
        body: "A side path leads into untamed land. A lone beast may be waiting.",
        choices: {
          explore: "Follow the trail (wild battle)",
          leave: "Stay on the road (+12 gold)",
        },
      },
    },
    shop: {
      heal: "Heal party 50% and restore moves",
      buffAtk: "+2 ATK to party",
      buffDef: "+2 DEF to party",
      recruit: "Recruit",
      sell: "Sell a beast",
    },
    ui: {
      eyebrow: "Roguelike",
      title: "Beast Path",
      lead: "Choose a starter, pick your path through battles, wild areas, shops and events, capture beasts, and face the boss.",
      gold: "Gold",
      party: "Party",
      reserve: "Reserve",
      reserveHint: "Swap beasts between your party and reserve.",
      reserveEmpty: "No beasts in reserve.",
      reserveOpen: "Reserve",
      reserveClose: "Close",
      reserveSwap: "Swap into party",
      reserveToParty: "To party",
      partyToReserve: "To reserve",
      mapHint: "Follow the paths and choose an open node.",
      chooseStarter: "Choose your first beast",
      starterHint: "This companion starts your run. You can capture more later.",
      fight: "Fight",
      fightRound: "Fight",
      turnOrder: "Turn order",
      chooseMove: "Choose a move",
      actionsPanel: "Actions",
      fullscreenEnter: "Fullscreen",
      fullscreenExit: "Exit fullscreen",
      emptyMove: "Empty",
      skipMove: "Skip",
      chooseTarget: "Choose a target",
      planned: "Ready",
      skipped: "Skip",
      needPlans: "Assign a move (or skip) for every living beast.",
      logSkip: "waits",
      yourTurn: "Plan moves for your beasts, then press Fight.",
      enemyTurn: "Resolving…",
      resolving: "Resolving round…",
      victoryBattle: "Victory!",
      defeatBattle: "Your party fell.",
      captureAction: "Capture",
      captureArmed: "Capture ready — press Fight",
      captureSuccess: "was captured!",
      captureFail: "broke free!",
      captureHint: "Capture attempt: your party skips moves this round.",
      sentToReserve: "sent to reserve",
      claimRewards: "Continue",
      shopTitle: "Roadside shop",
      buy: "Buy",
      leaveShop: "Leave shop",
      restTitle: "Rest site",
      restBody: "A safe hollow. Heal 50% max HP and restore move uses.",
      restAction: "Rest (heal 50%)",
      continue: "Continue",
      newRun: "New run",
      runVictory: "The path is cleared. The Abyss Hydra falls.",
      runDefeat: "The expedition ends here. Start again?",
      emptyParty: "No room in the party (max 6).",
      cannotReleaseLast: "You need at least one beast.",
      cannotSellLast: "You must keep at least one beast.",
      shopSellOnce: "You can only sell one beast per shop visit.",
      shopSold: "Sold",
      shopSellTitle: "Sell a beast",
      shopSellOpen: "Sell a beast",
      shopSellPick: "Choose a beast to sell",
      shopSellAction: "Sell",
      shopSellClose: "Cancel",
      notEnoughGold: "Not enough gold.",
      logAttack: "hits",
      logFaint: "faints",
      logUses: "uses",
      logHeal: "recovers",
      logBuff: "gains",
      logGuard: "braces",
      logLearned: "learned",
      logForgot: "forgot",
      rewardGold: "Gold earned",
      rewardXp: "XP shared",
      level: "Lv",
      hp: "HP",
      atk: "ATK",
      def: "DEF",
      spd: "SPD",
      available: "Open",
      visited: "Cleared",
      locked: "Locked",
      current: "Here",
      artPlaceholder: "Art",
      scrollLeft: "Scroll map left",
      scrollRight: "Scroll map right",
      previewDamage: "Damage",
      previewHeal: "Heal",
      previewBuff: "Buff",
      previewGuard: "Guard",
      uses: "Uses",
      noUses: "No uses left",
      targets: "Targets",
      selfTarget: "Self",
    },
  },
  es: {
    species: {
      "ember-cub": "Cachorro Ember",
      "tide-sprite": "Duende de Marea",
      "gale-finch": "Pinzón Gale",
      "moss-brute": "Bruto Musgo",
      "spark-mite": "Ácaro Chispa",
      "shade-pup": "Cachorro Sombra",
      "cinder-fox": "Zorro Ceniza",
      "reef-guard": "Guardián de Arrecife",
      "storm-owl": "Búho Tormenta",
      "root-titan": "Titán Raíz",
      "volt-drake": "Draco Volt",
      "night-wraith": "Espectro Nocturno",
      "boss-hydra": "Hidra del Abismo",
    },
    elements: {
      ember: "Ember",
      tide: "Marea",
      gale: "Vendaval",
      moss: "Musgo",
      spark: "Chispa",
      shade: "Sombra",
    },
    habitats: {
      cave: "Cueva",
      grassland: "Pastizal",
      forest: "Bosque",
      river: "Río",
      sea: "Mar",
      beach: "Playa",
      desert: "Desierto",
      swamp: "Pantano",
    },
    nodes: {
      start: "Campamento",
      battle: "Pelea",
      elite: "Élite",
      shop: "Tienda",
      event: "Evento",
      rest: "Descanso",
      boss: "Boss",
      habitat: "Salvaje",
    },
    moves: moveCopyEs,
    events: {
      spring: {
        title: "Manantial oculto",
        body: "Un manantial cálido brota entre las piedras. Tus bestias beben.",
        choices: {
          heal: "Descansar y curar al equipo (50% + movimientos)",
          gold: "Embotellar el agua (+18 oro)",
        },
      },
      shrine: {
        title: "Santuario erosionado",
        body: "Un santuario antiguo vibra con poder residual. Algo responde a tu toque.",
        choices: {
          atk: "Ofrecer un colmillo (+2 ATK a todos)",
          def: "Ofrecer un caparazón (+2 DEF a todos)",
        },
      },
      trader: {
        title: "Comerciante errante",
        body: "Un comerciante enmascarado ofrece una jaula inquieta. Adentro, una bestia salvaje te observa.",
        choices: {
          take: "Aceptar la bestia (si hay lugar)",
          gold: "Comprar la jaula vacía (+25 oro)",
        },
      },
      curse: {
        title: "Matorral maldito",
        body: "Las espinas gotean savia nocturna. Cruzar tiene un precio.",
        choices: {
          pay: "Abrirse paso (−8 HP cada uno)",
          bribe: "Dejar una ofrenda (−20 oro, seguro)",
        },
      },
      campfire: {
        title: "Fogata tranquila",
        body: "Las brasas crepitan. Tus bestias se acurrucan y recuperan.",
        choices: {
          heal: "Dormir hasta el alba (cura 50% + movimientos)",
          train: "Entrenar suave (+1 ATK, cura 50% + movimientos)",
        },
      },
      release: {
        title: "Pradera abierta",
        body: "Un claro tranquilo. Una de tus bestias podría volver a la naturaleza.",
        choices: {
          keep: "Conservar todo el equipo",
          free: "Liberar",
        },
      },
      wilds: {
        title: "Sendero salvaje",
        body: "Un desvío lleva a tierra indómita. Una bestia solitaria puede estar esperando.",
        choices: {
          explore: "Seguir el sendero (pelea salvaje)",
          leave: "Quedarse en el camino (+12 oro)",
        },
      },
    },
    shop: {
      heal: "Curar 50% del equipo y restaurar movimientos",
      buffAtk: "+2 ATK al equipo",
      buffDef: "+2 DEF al equipo",
      recruit: "Reclutar",
      sell: "Vender una bestia",
    },
    ui: {
      eyebrow: "Roguelike",
      title: "Camino de Bestias",
      lead: "Elegí un inicial, avanzá por peleas, zonas salvajes, tiendas y eventos, capturá bestias y enfrentá al boss.",
      gold: "Oro",
      party: "Equipo",
      reserve: "Reserva",
      reserveHint: "Intercambiá bestias entre el equipo y la reserva.",
      reserveEmpty: "No hay bestias en la reserva.",
      reserveOpen: "Reserva",
      reserveClose: "Cerrar",
      reserveSwap: "Pasar al equipo",
      reserveToParty: "Al equipo",
      partyToReserve: "A la reserva",
      mapHint: "Seguí los caminos y elegí un nodo abierto.",
      chooseStarter: "Elegí tu primera bestia",
      starterHint: "Esta compañía inicia la run. Después podés capturar más.",
      fight: "Pelear",
      fightRound: "Lucha",
      turnOrder: "Orden de turnos",
      chooseMove: "Elegí un movimiento",
      actionsPanel: "Acciones",
      fullscreenEnter: "Pantalla completa",
      fullscreenExit: "Salir de pantalla completa",
      emptyMove: "Vacío",
      skipMove: "Omitir",
      chooseTarget: "Elegí un objetivo",
      planned: "Listo",
      skipped: "Omite",
      needPlans: "Asigná un movimiento (u omití) para cada bestia viva.",
      logSkip: "espera",
      yourTurn: "Planeá los movimientos y después apretá Lucha.",
      enemyTurn: "Resolviendo…",
      resolving: "Resolviendo ronda…",
      victoryBattle: "¡Victoria!",
      defeatBattle: "Tu equipo cayó.",
      captureAction: "Capturar",
      captureArmed: "Captura lista — apretá Lucha",
      captureSuccess: "fue capturada!",
      captureFail: "se liberó!",
      captureHint: "Intento de captura: tu equipo no usa movimientos esta ronda.",
      sentToReserve: "enviada a la reserva",
      claimRewards: "Continuar",
      shopTitle: "Tienda del camino",
      buy: "Comprar",
      leaveShop: "Salir de la tienda",
      restTitle: "Sitio de descanso",
      restBody: "Un hueco seguro. Cura el 50% de la vida máxima y restaura los usos de movimientos.",
      restAction: "Descansar (cura 50%)",
      continue: "Continuar",
      newRun: "Nueva run",
      runVictory: "El camino quedó limpio. La Hidra del Abismo cae.",
      runDefeat: "La expedición termina acá. ¿Empezar de nuevo?",
      emptyParty: "No hay lugar en el equipo (máx. 6).",
      cannotReleaseLast: "Necesitás al menos una bestia.",
      cannotSellLast: "Tenés que conservar al menos una bestia.",
      shopSellOnce: "Solo podés vender una bestia por visita a la tienda.",
      shopSold: "Vendiste",
      shopSellTitle: "Vender una bestia",
      shopSellOpen: "Vender una bestia",
      shopSellPick: "Elegí una bestia para vender",
      shopSellAction: "Vender",
      shopSellClose: "Cancelar",
      notEnoughGold: "No hay suficiente oro.",
      logAttack: "golpea a",
      logFaint: "cae",
      logUses: "usa",
      logHeal: "recupera",
      logBuff: "gana",
      logGuard: "se protege",
      logLearned: "aprendió",
      logForgot: "olvidó",
      rewardGold: "Oro ganado",
      rewardXp: "XP repartida",
      level: "Nv",
      hp: "HP",
      atk: "ATK",
      def: "DEF",
      spd: "SPD",
      available: "Abierto",
      visited: "Superado",
      locked: "Bloqueado",
      current: "Acá",
      artPlaceholder: "Arte",
      scrollLeft: "Desplazar mapa a la izquierda",
      scrollRight: "Desplazar mapa a la derecha",
      previewDamage: "Daño",
      previewHeal: "Cura",
      previewBuff: "Buff",
      previewGuard: "Guardia",
      uses: "Usos",
      noUses: "Sin usos",
      targets: "Objetivos",
      selfTarget: "Sí mismo",
    },
  },
};
